services:
  - type: web
    name: somar-doacoes
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production